platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: SpringBootSimpleRest

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootSimpleRest
    mvn package
    ls -la
    cd target
    ls -la
    cd ..
    chmod 777 target
    cp ./target/springbootsimplerest-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
    cp Dockerfile ../built-project
    ls -la
