platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }
inputs:
- name: SpringBootSimpleRest

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootSimpleRest
    ls -la
    if grep 'status="pass"' JunitReport.xml ; then
    echo "found"
    docker ps
    else
    echo "not found"
    fi
