resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/dhaneshande/jobfail.git
    branch: master

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: SpringBootSimpleRest, trigger: true}
  - task: build
    file: SpringBootSimpleRest/build.yml

